# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      
      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================
      
      - name: 📗 Classic template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
        #  output_action: pull-request
          output_action: commit
        #  delay: 120
          
      # ======================================================================================
      # 🧩 PLUGINS
      # ======================================================================================          
          
      # ======================================================================================
      # 📸 Website screenshot

      - name: 📸 Website screenshot
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
         # output_action: pull-request
          output_action: commit
         # delay: 120          
